services:
  tg-bot:
    build:  .
    image: tg-bot:latest
    container_name: tg-bot-weather
    env_file:
      - .env
    environment:
      - WEATHER_TOKEN=${WEATHER_TOKEN}
      - BOT_TOKEN=${BOT_TOKEN}
      - NASA_TOKEN=${NASA_TOKEN}
    restart: always